package com.example.philip.vibs;

import android.os.Bundle;
import android.support.annotation.NonNull;
import android.support.design.widget.BottomNavigationView;
import android.support.v4.app.Fragment;
import android.support.v4.app.FragmentTransaction;
import android.support.v7.app.ActionBar;
import android.support.v7.app.AppCompatActivity;
import android.support.v7.widget.DefaultItemAnimator;
import android.support.v7.widget.LinearLayoutManager;
import android.support.v7.widget.RecyclerView;
import android.support.v7.widget.Toolbar;
import android.util.Log;
import android.view.MenuItem;
import android.view.WindowManager;
import android.widget.TextView;

import com.couchbase.lite.CouchbaseLiteException;
import com.couchbase.lite.Database;
import com.couchbase.lite.Document;
import com.couchbase.lite.Manager;
import com.couchbase.lite.android.AndroidContext;
import com.couchbase.lite.replicator.Replication;
import com.example.philip.vibs.model.ActionItem;
import com.example.philip.vibs.model.BirthdayItem;
import com.example.philip.vibs.model.CalendarItem;
import com.example.philip.vibs.model.DocumentItem;
import com.example.philip.vibs.model.InboxItem;
import com.example.philip.vibs.model.MultiMediaItem;
import com.example.philip.vibs.model.StoryItem;

import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import static com.example.philip.vibs.DataHolder.feedObjectList;
import static com.example.philip.vibs.DataHolder.inboxItemList;

public class InboxActivity extends AppCompatActivity {

    private ActionBar actionToolbar;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_inbox);
        createProtoListFeed();
        createProtoListInbox();
        createCalendarItemList();
        BottomNavigationView navigation = (BottomNavigationView) findViewById(R.id.navigation);
        navigation.setOnNavigationItemSelectedListener(mOnNavigationItemSelectedListener);
        Fragment fragment = new InboxFragment();
        loadFragment(fragment);
        connectToCloudBase();
        actionToolbar = getSupportActionBar();
        actionToolbar.setTitle("Inbox");

    }

    private void connectToCloudBase() {
        Manager manager = null;
        try {
            manager = new Manager(new AndroidContext(getApplicationContext()), Manager.DEFAULT_OPTIONS);
        } catch (IOException e) {
            e.printStackTrace();
        }
// Create or open the database named app
        Database database = null;
        try {
            database = manager.getDatabase("app");
        } catch (CouchbaseLiteException e) {
            e.printStackTrace();
        }
// The properties that will be saved on the document
        Map<String, Object> properties = new HashMap<String, Object>();
        properties.put("title", "Couchbase Mobile");
        properties.put("sdk", "Android");
// Create a new document
        Document document = database.createDocument();
// Save the document to the database
        try {
            document.putProperties(properties);
        } catch (CouchbaseLiteException e) {
            e.printStackTrace();
        }
// Log the document ID (generated by the database)
// and properties
        Log.d("app", String.format("Document ID :: %s", document.getId()));
        Log.d("app", String.format("Learning %s with %s", (String) document.getProperty("title"), (String) document.getProperty("sdk")));

// Create replicators to push & pull changes to & from Sync Gateway.
        URL url = null;
        try {
            url = new URL("http://10.0.2.2:4984/hello");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        Replication push = database.createPushReplication(url);
        Replication pull = database.createPullReplication(url);
        push.setContinuous(true);
        pull.setContinuous(true);

// Start replicators
        push.start();
        pull.start();
    }

    private BottomNavigationView.OnNavigationItemSelectedListener mOnNavigationItemSelectedListener
            = new BottomNavigationView.OnNavigationItemSelectedListener() {

        @Override
        public boolean onNavigationItemSelected(@NonNull MenuItem item) {
            Fragment fragment;
            switch (item.getItemId()) {
                case R.id.navigation_planner:
                    fragment = new CalendarFragment();
                    loadFragment(fragment);
                    return true;
                case R.id.navigation_inbox:
                    fragment = new InboxFragment();
                    loadFragment(fragment);

                    return true;
                case R.id.navigation_notifications:
                    fragment = new InboxFragment();
                    loadFragment(fragment);
                    return true;
            }
            return false;
        }
    };

    private void loadFragment(Fragment fragment) {
        // load fragment
        FragmentTransaction transaction = getSupportFragmentManager().beginTransaction();
        transaction.replace(R.id.frame_container, fragment);
        transaction.addToBackStack(null);
        transaction.commit();
    }
    private void createProtoListFeed() {

        DataHolder.feedObjectList = new ArrayList<>();
        DataHolder.feedObjectList.clear();
        DataHolder.feedObjectList.add(new MultiMediaItem("Thomas Wagner", R.drawable.profil_round_3, "Zugspitze", new Date(), R.drawable.zugspitze));
        DataHolder.feedObjectList.add(new DocumentItem("Matthias Fischer", "Impressive PDF File", "impressive.pdf", new Date(), R.drawable.profile_round_2));
        DataHolder.feedObjectList.add(new BirthdayItem("Peter Griffin", R.drawable.profile_round_3, 43));
        DataHolder.feedObjectList.add(new ActionItem("Matthias Atze", R.drawable.round_profile, "Lust auf schwimmen?", "Universität Regensburg", new Date(), new Date()));
        DataHolder.feedObjectList.add(new StoryItem("Lisa Kläss", "Shisha rauchen", "Unter Geschichte versteht man im Allgemeinen diejenigen Aspekte der Vergangenheit, derer Menschen gedenken und die sie deuten, um sich über den Charakter zeitlichen Wandels und dessen Auswirkungen auf die eigene Gegenwart und Zukunft zu orientieren", new Date(), R.drawable.profile_round_2));
        DataHolder.feedObjectList.add(new BirthdayItem("Jochen Schweizer", R.drawable.profile_round_2, 20));
        DataHolder.feedObjectList.add(new DocumentItem("Done Dane", "Zusammenfassung IT-Security", "zusammenfassung.pdf", new Date(), R.drawable.profile_round_2));
        DataHolder.feedObjectList.add(new ActionItem("Jens Hartmann", R.drawable.profil_round_3, "Tanzen?", "Wörhdbad", new Date(), new Date()));
        DataHolder.feedObjectList.add(new StoryItem("Maria Maria", "Klausrrelevant", "Eine Klausur (Pädagogik) bezeic, hnet eine schriftliche Prüfungsarbeit, die in der Regel gleichzeitig mit anderen Teilnehmern in einer festgelegten Zeitspanne unter Aufsicht angefertigt wird[1]. In der Regel dient sie als Leistungskontrolle der qualitativen Leistungsbewertung und führt über die Notengebung zu differenzierenden Ergebnissen. In der Schule ersetzt sie in der Sekundarstufe II die Klassenarbeit und ist in der Regel mehrstündig konzipiert. Mit Ausnahme von zentral gestellten Abiturklausuren oder Vergleichsklausuren wird sie vom jeweiligen Fachlehrer gestellt, zeitnah mithilfe eines transparenten Bewertungsschemas korrigiert, benotet und den Prüflingen ausgehändigt.", new Date(), R.drawable.profile_round_2));
        DataHolder.feedObjectList.add(new BirthdayItem("Peter Lustig", R.drawable.profile_round_3, 55));
        DataHolder.feedObjectList.add(new StoryItem("Günter Heiss", "Gin Tonic Rezept", "Gin Tonic (engl. gin and tonic, kurz G & T) ist ein klassischer Longdrink aus Gin und Tonic Water. Das Mischverhältnis variiert je nach Geschmack von 1:1 bis 1:3 oder höher. Wie die meisten Highballs, in der Regel aus lediglich einer Spirituose und einem kohlensäurehaltigen Filler bestehende Mixgetränke, wird Gin Tonic direkt im Glas zubereitet (englisch built in glass), indem man die Zutaten über Eiswürfel gießt und vorsichtig umrührt.", new Date(), R.drawable.profile_round_2));
        DataHolder.feedObjectList.add(new ActionItem("Jonas Bauer", R.drawable.round_profile, "Ballern?", "Vinyl", new Date(), new Date()));
        DataHolder.feedObjectList.add(new MultiMediaItem("Matthias Fischer", R.drawable.profil_round_3, "Jahninsel", new Date(), R.drawable.jahninsel));

    }

    private void createProtoListInbox() {

        DataHolder.inboxItemList = new ArrayList<>();
        DataHolder.inboxItemList.clear();
        DataHolder.inboxItemList.add(new InboxItem("Philip Empl", R.drawable.profil_round_3, "Gestern wars echt lustig!", new Date()));
        DataHolder.inboxItemList.add(new InboxItem("Joachim Witt", R.drawable.profile_round_2, "Heute Vorlesung um 17:00 Uhr und danach baden", new Date()));
        DataHolder.inboxItemList.add(new InboxItem("Dennis Otter", R.drawable.profile_round_3, "Hallo Hans, willst du heute schiwmmen gehen?", new Date()));
        DataHolder.inboxItemList.add(new InboxItem("PFranziska Weidler", R.drawable.round_profile, "Was machst du heute noch?", new Date()));
        DataHolder.inboxItemList.add(new InboxItem("Frank Sinatra", R.drawable.profil_round_3, "Ne, wir waren auf der Dult und meine Band und ich haben da bissl aufgezeockt", new Date()));
        DataHolder.inboxItemList.add(new InboxItem("Channing Tatum", R.drawable.profile_round_2, "hahah, du bist aber witzig - nicht", new Date()));
        DataHolder.inboxItemList.add(new InboxItem("Kurt Mauer", R.drawable.profile_round_3, "Oida, a Döner wär scho was feines", new Date()));
        DataHolder.inboxItemList.add(new InboxItem("Sina Haller", R.drawable.round_profile, "mei, so sans halt die Mädels. Immer wieder ansterngend und trotzdem hammas lieb", new Date()));

        }
private void createCalendarItemList()
{
    DataHolder.calendarItemsList = new ArrayList<>();
    DataHolder.calendarItemsList.add(new CalendarItem("Jahninsel Grillen", new Date(), new Date()));
    DataHolder.calendarItemsList.add(new CalendarItem("Bowling Abend", new Date(), new Date()));
    DataHolder.calendarItemsList.add(new CalendarItem("Romantisches Dinner", new Date(), new Date()));
    DataHolder.calendarItemsList.add(new CalendarItem("Vier Jahreszeiten Konzert", new Date(), new Date()));
    DataHolder.calendarItemsList.add(new CalendarItem("Grundloses Besäufnis", new Date(), new Date()));
    DataHolder.calendarItemsList.add(new CalendarItem("Vernisage", new Date(), new Date()));
    DataHolder.calendarItemsList.add(new CalendarItem("Go So Hard Digga Abend", new Date(), new Date()));
    DataHolder.calendarItemsList.add(new CalendarItem("Hanuta Spaß", new Date(), new Date()));
    DataHolder.calendarItemsList.add(new CalendarItem("Yo was geht", new Date(), new Date()));


}
}
